export default [
  {
    name: "Классическая шаурма",
    image: "https://mcdoner.by/asset/63eba56a3e4875a605150ab0?resize=true",
    ingredients: ["Лаваш", "Курица", "Помидоры", "Огурцы", "Лук", "Соус"],
    size: ["250g", "400g"],
    price: [250, 300], 
  },
  {
    name: "Шаурма с курицей",
    image: "https://mcdoner.by/asset/63eba60d3e4875a605150ac8?resize=true",
    ingredients: [
      "Лаваш",
      "Курица",
      "Маринованный огурец",
      "Картофель фри",
      "Тахини",
    ],
    size: ["230g", "380g"],
    price: [270, 320], 
  },
  {
    name: "Шаурма с говядиной",
    image: "https://mcdoner.by/asset/63eba60d3e4875a605150abd?resize=true",
    ingredients: [
      "Лаваш",
      "Говядина",
      "Огурцы",
      "Томаты",
      "Лук",
      "Чесночный соус",
    ],
    size: ["270g", "420g"],
    price: [300, 350], 
  },
  {
    name: "Шаурма с бараниной",
    image: "https://mcdoner.by/asset/65b4c903fc2ea4f97c11364e?resize=true",
    ingredients: [
      "Лаваш",
      "Баранина",
      "Лук",
      "Помидоры",
      "Специи",
      "Соус с йогуртом",
    ],
    size: ["280g", "450g"],
    price: [350, 400], 
  },
  {
    name: "Шаурма с овощами",
    image: "https://mcdoner.by/asset/65d2fe76fc2ea4f97c113b2c?resize=true",
    ingredients: [
      "Лаваш",
      "Огурцы",
      "Помидоры",
      "Перец",
      "Лук",
      "Листья салата",
      "Хумус",
    ],
    size: ["220g", "360g"],
    price: [200, 240], 
  },
  {
    name: "Шаурма с курицей и картошкой фри",
    image: "https://mcdoner.by/asset/63ea39223e4875a6051509c6?resize=true",
    ingredients: [
      "Лаваш",
      "Курица",
      "Картофель фри",
      "Лук",
      "Томат",
      "Майонез",
      "Кетчуп",
    ],
    size: ["280g", "420g"],
    price: [280, 320], 
  },
  {
    name: "Шаурма с соусом тахини",
    image: "https://mcdoner.by/asset/63ea39223e4875a6051509d0?resize=true",
    ingredients: [
      "Лаваш",
      "Курица",
      "Тахини",
      "Огурцы",
      "Помидоры",
      "Листья салата",
    ],
    size: ["240g", "380g"],
    price: [260, 300], 
  },
  {
    name: "Шаурма с сыром",
    image: "https://mcdoner.by/asset/63ea39c53e4875a6051509d6?resize=true",
    ingredients: [
      "Лаваш",
      "Курица",
      "Твердый сыр",
      "Помидоры",
      "Лук",
      "Сметана",
    ],
    size: ["250g", "400g"],
    price: [290, 340], 
  },
  {
    name: "Шаурма с острым соусом",
    image: "https://mcdoner.by/asset/63ea39c53e4875a6051509ef?resize=true",
    ingredients: [
      "Лаваш",
      "Говядина",
      "Огурцы",
      "Лук",
      "Помидоры",
      "Острый соус",
    ],
    size: ["260g", "410g"],
    price: [310, 350], 
  },
];
